project:
  type: book
  execute-dir: project
  output-dir: _book
  preview:
    port: 5690
    host: 127.0.0.1
    browser: true
    watch-inputs: true
    navigate: true

metadata-files:
  - _authors.yml
  - _affiliations.yml

book:
  title: "{{< var book.title >}}"
  subtitle: "{{< var book.subtitle >}}"
  date: today
  date-format: "{{< var book.date-format >}}"
  accessed: today
  language: en
  favicon: images/docker-logo.svg
  site-url: "https://lennartwittkuhn.com/container-book"
  repo-url: "https://github.com/lnnrtwttkhn/container-book"
  repo-branch: "main"
  issue-url: "{{< var book.repo-url >}}/issues"
  repo-actions: [edit, source, issue]
  reader-mode: false
  search:
    location: navbar
    type: overlay
    limit: 20
    copy-button: true
  page-navigation: true
  back-to-top-navigation: true
  
  chapters:
    - index.qmd
    - contents.qmd
    - chapters/containers.qmd
    - chapters/command-line.qmd
    - chapters/docker-installation.qmd
    - chapters/docker-start.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    include-before-body: plausible.html
    link-external-newwindow: true
    link-external-icon: false
    bibliography: references.bib
    csl: chicago-author-date-note.csl
    citations-hover: true
    citation-location: document
    citeproc: true
